name: Executar Robô de Download Automático

on:
  schedule:
    # Roda automaticamente a cada 2 horas (00:00, 02:00, 04:00, etc)
    - cron: '0 */2 * * *'
  workflow_dispatch:
    inputs:
      url_jogo:
        description: 'Link do jogo (deixe em branco para atualizar TODOS)'
        required: false
        default: ''

jobs:
  extrair:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Playwright e Dependencias
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Executar Robô
        run: |
          if [ -n "${{ github.event.inputs.url_jogo }}" ]; then
            python extrair.py "${{ github.event.inputs.url_jogo }}"
          else
            python extrair.py
          fi
